### ISSUE TITLE
Help wanted !!! There is a bug that needs your attention, thanks in advance!

### ISSUE THREAD

**Issue by yuandongx** [ansible-collections/ansible.netcommon#201] opened 2021-01-08 06:54 UTC
##### SUMMARY

I have missed a bug with [code bock](https://github.com/ansible-collections/ansible.netcommon/blob/486a01bae9e46b92d9829d2d571e78121965ade4/plugins/connection/network_cli.py#L1014) when I run a command `access-list test-acl-1 extended permit tcp object-group IP_Test  host 10.22.5.38 eq 8080`, and `IP_Test ` does not exist on my device. An exception wiil be raised, but not.
The reason of which is that length of error message  is too long to handle with method `_find_prompt`.
The method will only handle a block with length less than 256, but with length more than 256,  `error_response` will be `None` again.So the `network_cli` will not work well.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

plugins/connection/network_cli.py
##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by yuandongx** [comment] 2021-01-12 09:35
```
 def _find_prompt(self, response):
        """Searches the buffered response for a matching command prompt
        """
        errored_response = None
        is_error_message = False

        for stderr_regex in self._terminal_stderr_re:
            if stderr_regex.search(response):
                is_error_message = True
                self._log_messages(
                    "matched error regex (terminal_stderr_re) '%s' from response '%s'"
                    % (stderr_regex.pattern, response)
                )
                # Check if error response ends with command prompt if not
                # receive it buffered prompt
                for stdout_regex in self._terminal_stdout_re:
                    match = stdout_regex.search(response)
                    if match:
                        errored_response = response
                        self._matched_pattern = stdout_regex.pattern
                        self._matched_prompt = match.group()
                        self._log_messages(
                            "matched stdout regex (terminal_stdout_re) '%s' from error response '%s'"
                            % (self._matched_pattern, errored_response)
                        )
                        break
                else:
                    self._log_messages(
                        "Ignoring matched error regex (terminal_stderr_re) '%s' from response '%s' as the cli prompt is not in the same response"
                        % (stderr_regex.pattern, response)
                    )
                if errored_response:
```

### These Lines
```
          for stdout_regex in self._terminal_stdout_re:
                    match = stdout_regex.search(response)
                    if match:
                        errored_response = response
```
Regex will not match `response` and errored_response  will still be `None`, when an error message length is more than 255.
Becase `_find_prompt`  recevied not more than 256 chars, and next  `response` fragment have no `error:` regexp.

**Comment by yuandongx** [comment] 2021-01-12 09:54
Maybe relate to ansible-collections/cisco.asa#83

**Comment by yuandongx** [comment] 2021-01-12 09:57
cc @ganeshrn @CaptTrews  @pabelanger  @Qalthos

**Comment by Qalthos** [comment] 2021-01-12 22:39
This appears to be a duplicate of #16. Thanks for reminding us that this really needs to get fixed

**Closed by Qalthos** 2021-01-12 22:39 UTC
