### ISSUE TITLE
'multiple repeat at position 21' for platform type ansible.netcommon.restconf

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible-collections/ansible.netcommon#383] opened 2022-03-21 13:38 UTC
##### SUMMARY
Using 'ansible_connection: ansible.netcommon.httpapi' with 'ansible_network_os: ansible.netcommon.restconf' fails with [ansible.netcommon.restconf_get](https://docs.ansible.com/ansible/latest/collections/ansible/netcommon/restconf_get_module.html#notes).

The issue report is a follow up of [that issue](https://github.com/ansible-collections/ansible.netcommon/issues/356) which has begun as ```unable to load API plugin for platform type ansible.netcommon.restconf ``` then evolved into ```multiple repeat at position 21``` and has been closed without being fully tested.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
restconf_get

##### ANSIBLE VERSION
```console
$ ansible --version
  ansible [core 2.12.3]
  config file = /etc/ansible/ansible.cfg
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /opt
  executable location = /usr/local/bin/ansible
  python version = 3.9.9 (main, Jan 12 2022, 16:10:51) [GCC 11.2.0]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION
```
$ ansible-galaxy collection list --server release_galaxy ansible.netcommon

# /usr/local/lib/python3.9/dist-packages/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 2.5.1  

# /opt/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 2.6.1  
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = redis
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = localhost:<port>:0:<password>
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 259200
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/opt']
DEFAULT_EXECUTABLE(/etc/ansible/ansible.cfg) = /bin/bash
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 1000
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = replace
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_PRIVATE_ROLE_VARS(/etc/ansible/ansible.cfg) = False
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 180
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = ssh
ENABLE_TASK_DEBUGGER(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = True
INJECT_FACTS_AS_VARS(/etc/ansible/ansible.cfg) = True
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 3599
PERSISTENT_CONNECT_RETRY_TIMEOUT(/etc/ansible/ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 3600
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
SHOW_CUSTOM_STATS(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
host: Ubuntu 21.10 impish
target: CSR1kv IOS-XE 17.3.1a

##### STEPS TO REPRODUCE
playbook:
```
- name: Getting RESTConf API root
  hosts:
        - all
  vars:
        ansible_connection: ansible.netcommon.httpapi
        ansible_network_os: ansible.netcommon.restconf
  tasks:
        - name: Getting api root
          ansible.netcommon.restconf_get:
                content: "all"
                output: "xml"
                path: "/.well-known/host-meta"
```

##### EXPECTED RESULTS
The following should be returned:
```
<XRD xmlns='http://docs.oasis-open.org/ns/xri/xrd-1.0'>
    <Link rel='restconf' href='/restconf'/>
</XRD>
```

##### ACTUAL RESULTS
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/ansible/executor/task_executor.py", line 515, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/local/lib/python3.9/dist-packages/ansible/playbook/task.py", line 285, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/local/lib/python3.9/dist-packages/ansible/playbook/base.py", line 650, in post_validate
    value = templar.template(getattr(self, name))
  File "/usr/local/lib/python3.9/dist-packages/ansible/template/__init__.py", line 913, in template
    d[k] = self.template(
  File "/usr/local/lib/python3.9/dist-packages/ansible/template/__init__.py", line 869, in template
    result = self.do_template(
  File "/usr/local/lib/python3.9/dist-packages/ansible/template/__init__.py", line 1139, in do_template
    res = j2_concat(rf)
  File "<template>", line 18, in root
  File "/usr/local/lib/python3.9/dist-packages/ansible/template/__init__.py", line 298, in wrapper
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/ansible/plugins/filter/core.py", line 162, in regex_search
    match = re.search(regex, value, flags)
  File "/usr/lib/python3.9/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.9/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.9/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.9/sre_parse.py", line 671, in _parse
    raise source.error("multiple repeat",
re.error: multiple repeat at position 21
fatal: [CSR1000v-17.3.1a -> localhost]: FAILED! => changed=false
```

**Comment by jean-christophe-manciot** [comment] 2022-04-28 09:38
Same issue with netcommon==3.0.0

**Comment by Qalthos** [comment] 2022-05-16 15:21
So first off, I am completely unable to reproduce this
```
playbooks$ ansible --version
ansible [core 2.12.5]
  config file = None
  configured module search path = ['/home/nate/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nate/.local/pipx/venvs/ansible-core/lib/python3.10/site-packages/ansible
  ansible collection location = /home/nate/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/nate/.local/bin/ansible
  python version = 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
  jinja version = 3.1.2
  libyaml = True
playbooks$ ansible-galaxy collection list

# /home/nate/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 3.0.0  
ansible.utils     2.6.1  
playbooks$ cat restconf.yaml 
---
- name: Get RESTConf API root
  hosts: 
    - restconf

  vars:
    ansible_connection: ansible.netcommon.httpapi
    ansible_network_os: ansible.netcommon.restconf
    ansible_httpapi_restconf_root: /

  tasks:
    - name: Getting api root
      ansible.netcommon.restconf_get:
        content: "all"
        path: "/.well-known/host-meta"
playbooks$ ansible-playbook -i hosts.ini restconf.yaml -v
No config file found; using defaults

PLAY [Get RESTConf API root] ***************************************************

TASK [Gathering Facts] *********************************************************
ok: [restconf]

TASK [Getting api root] ********************************************************
ok: [restconf] => {"changed": false, "response": ""}

PLAY RECAP *********************************************************************
restconf              : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
There are, I think, a few things going on here.

The first is that you probably shouldn't be using the `restconf` httpapi plugin to read your host-meta file to determine where restconf lives. If you absolutely need to do this on a host-by-host basis and can't assume a common path, the [`ansible.builtin.uri`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/uri_module.html) module is much better suited to reading arbitrary URIs and returning their contents for processing. The `host-meta` file is not in the restconf root (presumably anyway? It would not be a very good .well-known dir if you had to read the contents to find out where it lived), and it also isn't (again, presuming something isn't seriously wonky with your device) an `application/yang-data+json` or  `application/yang-data+xml` file, the only two media types `restconf` supports.

Incidentally, the run above returns  empty string instead of the contents of the host-meta file because of a bug in restconf when it encounters non-JSON data, which will be addressed by https://github.com/ansible-collections/ansible.netcommon/pull/427. 

But all of that isn't even the issue here, because your error message shows that you aren't even running the task yet. Ansible is failing to parse all the variables in your playbook, and by the error, this is presumably because of some templating somewhere. Assuming the playbook you have provided is the one you are actually using, this should be an issue somewhere in your inventory, as I don't see anything else that would trigger templating.

Given that this results in a traceback, I would suggest opening an issue against ansible/ansible for this, even if you find the issue on your own, as this is not great feedback on what is going on here.

**Closed by Qalthos** 2022-05-16 15:21 UTC

**Comment by jean-christophe-manciot** [comment] 2022-06-08 08:02
@Qalthos 
Sorry for the late reply.

I stand by this bug report.

> So first off, I am completely unable to reproduce this

Because you did not reproduce the same call: you left out the ```output``` parameter to its default value, which is ... 'json'.
This **detail changes everything** as I confirm that with json, there is simply no issue.
This issue is still there, even with netcommon 3.0.1.

As a side note, considering all the many types of RESTConf implementations I'm daeling with, this play is made to
- make sure that 'restconf' is indeed the root; as specified by [RFC 8040](https://datatracker.ietf.org/doc/html/rfc8040#section-3.1),  "a RESTCONF client MUST determine the root of the RESTCONF API".
- make sure that the server version has not changed as specified by [RFC 8040](https://datatracker.ietf.org/doc/html/rfc8040#section-1.5)

I do agree with you though that the uri module would be best suited for this particular situation.

**Comment by jean-christophe-manciot** [comment] 2022-06-08 08:30
I have the same issue with:
```
        - name: Getting api resources
          ansible.netcommon.restconf_get:
                content: "all"
                output: "json"
                path: "/restconf"
```
