### ISSUE TITLE
Reserved address used as public in the documentation of ipaddr

### ISSUE THREAD

**Issue by dtantsur** [ansible-collections/ansible.netcommon#193] opened 2020-12-30 13:54 UTC
##### SUMMARY
The [ipaddr documentation](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters_ipaddr.html#getting-information-about-hosts-and-networks) lists '2001:db8:32c:faad::/64' as a public IP address. It's not, it's reserved per [IANA registry](https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml) and the Python's [ipaddress module](https://docs.python.org/3/library/ipaddress.html) agrees:
```
>>> import ipaddress
>>> ipaddress.ip_interface('2001:db8:32c:faad::/64').ip.is_global
False
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
ipaddr

##### ANSIBLE VERSION
Documentation

**Comment by Qalthos** [comment] 2021-01-06 13:08
Duplicate of #194

**Closed by Qalthos** 2021-01-06 13:08 UTC
