### ISSUE TITLE
regression: IPv4/IPv6 filter broken in ansible 2.x (works with 1.9.x)

### ISSUE THREAD

**Issue by nusenu** [ansible-collections/ansible.netcommon#136] opened 2020-09-13 08:50 UTC
Since the original issue got closed due to the migration, I'm opening it here again,
all the details can be found here:
ansible/ansible/issues/14829

**Comment by Qalthos** [comment] 2020-09-16 13:28
Have you tested it with the latest released version of the ansible.netcommon collection (1.2.1 at time of writing)? I'm failry certain this is a duplicate of #34 which was fixed by #89 and released with 1.1.0.

If it is still an issue, can you give me a more concrete example that still fails with the latest version? This is what I got:

```
PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => 
  tor_v4ips:
  - 192.168.1.176

TASK [debug] *******************************************************************
ok: [localhost] => 
  ipv4_count: '1'

TASK [debug] *******************************************************************
ok: [localhost] => 
  v6tmp: []

TASK [debug] *******************************************************************
ok: [localhost] => 
  tor_v6ips: []

TASK [setup IP list (1/2)] *****************************************************
ok: [localhost] => (item=['192.168.1.176', None])

TASK [debug] *******************************************************************
ok: [localhost] => 
  iptest:
    changed: false
    msg: All items completed
    results:
    - ansible_facts:
        ips:
          ipv4: 192.168.1.176
          ipv6: ''
      ansible_loop_var: item
      changed: false
      failed: false
      item:
      - 192.168.1.176
      - null

PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

which appears to be what you want from the previous issue.

**Comment by nusenu** [comment] 2020-09-18 23:21
Awesome to hear that there is a fix now after such a long time!

I'm on
ansible --version
ansible 2.9.13

and still get the error
```
Error was a <class 'ansible.errors.AnsibleError'>, original message: Unexpected templating type error occurred on ({{ tor_available_public_ipv6s[0:tor_ipv4_count|int] | ipv6('address') }}): 'bool' object is not subscriptable
``` 

but my
ansible/plugins/filter/ipaddr.py
does not appear to have the changes from #89 so I probably have to wait for
the next ansible version to get the fix.

I'll test again after the next ansible version.

**Comment by Qalthos** [comment] 2020-09-21 13:17
The good part of collections is that you don't have to wait... `ansible-galaxy collection install ansible.netcommon` and changing your filters from `ipv6` (or `ipv4` or `ipaddr` and so on) to `ansible.netcommon.ipv6` gets you the latest released version of the code without having to wait for the next ansible version.

https://docs.ansible.com/ansible/latest/user_guide/collections_using.html for more details on all of that.

**Comment by nusenu** [comment] 2020-09-23 19:52
ansible-galaxy is not for everyone. 

ansible-galaxy collection install ansible.netcommon
Process install dependency map
ERROR! Error when finding available api versions from default (https://galaxy.ansible.com) (HTTP Code: 403, Message: Forbidden)

https://github.com/ansible/galaxy/issues/1980

this is especially sad since I'm contributing
content to galaxy myself
https://galaxy.ansible.com/nusenu/relayor

**Comment by Qalthos** [comment] 2020-10-06 19:10
@nusenu can you update if this is fixed with ansible 2.10?

**Comment by nusenu** [comment] 2020-10-06 21:39
Yes, I'll let you know - currently waiting for ansible 2.10 packages.

**Comment by Qalthos** [comment] 2021-03-03 14:24
Are you still seeing this issue with Ansible 3.0.0?

**Comment by Qalthos** [comment] 2021-07-15 14:18
I'm closing this issue due to inactivity. If think this issue is still present, please either reopen this issue or open a new issue with a log from the most recent release of the netcommon collection

**Closed by Qalthos** 2021-07-15 14:18 UTC
Labels: needs_info
