### ISSUE TITLE
Private module attribute moved in Ansible Core 2.11

### ISSUE THREAD

**Issue by samdoran** [ansible-collections/ansible.netcommon#244] opened 2021-03-22 16:26 UTC
##### SUMMARY

Argument spec validation has changed in Ansible Core 2.11. The following private attribute call should be changed to use the public variable:

```
ansible.netcommon/plugins/module_utils/network/common/utils.py
291:                type_checker = self._module._CHECK_ARGUMENT_TYPES_DISPATCHER[  # --> ansible.module_utils.common.parameters.DEFAULT_TYPE_VALIDATORS
```

The private attribute is available for backwards compatibility only.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`ansible.netcommon/plugins/module_utils/network/common/utils.py`

##### ANSIBLE VERSION

```paste below
2.11
```

**Comment by Qalthos** [comment] 2021-03-24 12:42
Duplicate of #186

**Closed by Qalthos** 2021-03-24 12:42 UTC
